title: SouEdu
description: Dicas sobre o uso de licenças de software para estudantes de instituições de ensino superior e profissionalizantes.
baseurl: "/SouEdu"
url: "https://kelsoncm.github.io"
lang: pt-BR
theme: minima
